version: '3.8'
services:

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: apache
    ports:
    - "80:80" # normal php port for trafic and functionality
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
        - dev

  db:
    image: mysql:8.0
    hostname: localhost
    ports:
      - "3306:3306" # mysql connection port
    env_file:
      - .env
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
        - dev

  phpmyadmin:
        image: phpmyadmin
        container_name: datan-phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  
networks:
    dev:

volumes:
    db-data:

    