name: SSH Server Deploy
on: 
  push:
    branches: [master]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd public_html
            git pull origin master
            git status
            grunt
            cd scripts
            php update_version_asset
            git add application/helpers/utility_helper.php
            git commit -m "update asset version"
            git push
