name: SSH Server Deploy
on: 
  push:
    branches: [master]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.OMG_SECRET }}
          port: 22
          script: |
            ls
