# This is a basic workflow to help you get started with Actions

name: Docker Series Builds

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: echo Hello, world!
      - name: echo wget
        run: |
          wget -qO- https://ipecho.net/plain ; echo
